---
title: "Musical Ambiugous Figure Data Analysis"
output: R_Script
---
`

```{r}

library(ggplot2)
library(tidyverse)
library(ggpubr)
library(rstatix)
```
```{r}


df3 <- readfile <- read.csv("C:/Users/sarah/Documents/Mozart Survey/Data and analysis/Real/df_DV1_NoOut_June20.csv")

View(df3)

str(df3)
```


```{r}
df3 %>%
  group_by(Sonata_Section, Feature, Mod_Type, Expertise_Group) %>%
  get_summary_stats(DV, type = "mean_sd")
```

```{r}
bxp <- ggboxplot(
  df3, x = "Feature", y = "DV",
  color = "Mod_Type", palette = "jco",
  facet.by = "Sonata_Section", short.panel.labs = FALSE
  )
print(bxp)
```


```{r}
df3 %>%
  group_by(Sonata_Section, Feature, Mod_Type, Expertise_Group) %>%
  identify_outliers(DV)
```
```{r}
df3 %>%
  group_by(Sonata_Section, Feature, Mod_Type) %>%
  shapiro_test(DV)
```

```
```
```{r}
ggqqplot(df3, "DV", ggtheme = theme_bw()) +
  facet_grid(Sonata_Section ~ Feature ~ Mod_Type, labeller = "label_both")
```


```{r}
df3 %>%
  group_by(Sonata_Section, Feature, Mod_Type) %>%
  levene_test(DV ~ Expertise_Group)
```

```{r}
df3 %>%
  group_by(Sonata_Section, Feature, Mod_Type) %>%
  levene_test(DV ~ Excerpt_Familiarity)
```


```{r}
df3 %>%
  group_by(Sonata_Section, Feature, Mod_Type, Expertise_Group) %>%
  get_summary_stats(DV, type = "mean_sd")
```   



```{r}
# Compute RM ANOVA for within-subject factors only

res.aov3 <- anova_test(
  data = df3, dv = DV, wid = Random_IDs,
  within = c(Sonata_Section, Feature, Mod_Type)
  )
get_anova_table(res.aov3)
```



```{r}
# Compute RM ANOVA for within and between subjects factors
res.aov.bet3 <- anova_test(
  data = df3, dv = DV, wid = Random_IDs,
  within = c(Sonata_Section, Feature, Mod_Type), between=Expertise_Group
  )
get_anova_table(res.aov.bet3, correction="GG")
res.aov.bet3$`Sphericity Corrections`
```

```{r}

# Examine Main Effects

#Expertise

aov(DV ~ Expertise_Group, data = df3) %>% tukey_hsd()

df3 %>% t_test(DV ~ Expertise_Group, p.adjust.method = "bonferroni")

df3 %>% tukey_hsd(DV ~ Expertise_Group, conf.level = 0.95)

df3 %>%
  group_by(Expertise_Group) %>%
  get_summary_stats(DV, type = "mean_sd")

```

```{r}
# Examine Main Effects

#Feature

aov(DV ~ Feature, data = df3) %>% tukey_hsd()

df3 %>% t_test(DV ~ Feature, p.adjust.method = "bonferroni")

df3 %>% tukey_hsd(DV ~ Feature, conf.level = 0.95)

df3 %>%
  group_by(Feature) %>%
  get_summary_stats(DV, type = "mean_sd")

```














```{r}
#Mod Type

aov(DV ~ Mod_Type, data = df3) %>% tukey_hsd()

df3 %>% t_test(DV ~ Mod_Type, p.adjust.method = "bonferroni")

df3 %>% tukey_hsd(DV ~ Mod_Type, conf.level = 0.95)

df3 %>%
  group_by(Mod_Type) %>%
  get_summary_stats(DV, type = "mean_sd")
```


```{r}
# Two Way Interactions

# Expertise Group by Feature

aov(DV ~ Expertise_Group*Feature, data = df3) %>% tukey_hsd()

df3 %>%
  group_by(Expertise_Group) %>%
  tukey_hsd(DV ~ Feature, conf.level = 0.95)
  
df3 %>%
  group_by(Expertise_Group, Feature) %>%
  get_summary_stats(DV, type = "mean_sd")  


```


```{r}
# Expertise Group by Modulation Type

aov(DV ~ Expertise_Group*Mod_Type, data = df3) %>% tukey_hsd()

df3 %>%
  group_by(Expertise_Group) %>%
  tukey_hsd(DV ~ Mod_Type, conf.level = 0.95)
  
df3 %>%
  group_by(Expertise_Group, Mod_Type) %>%
  get_summary_stats(DV, type = "mean_sd")  


```



```{r}

# Sonata Section by Feature


aov(DV ~ Sonata_Section*Feature, data = df3) %>% tukey_hsd()

df3 %>%
  group_by(Sonata_Section) %>%
  tukey_hsd(DV ~ Feature, conf.level = 0.95)
  
df3 %>%
  group_by(Sonata_Section, Feature) %>%
  get_summary_stats(DV, type = "mean_sd")

```



```{r}
# Feature by Modulation Type

aov(DV ~ Feature*Mod_Type, data = df3) %>% tukey_hsd()

df3 %>%
  group_by(Feature) %>%
  tukey_hsd(DV ~ Mod_Type, conf.level = 0.95)
  
df3 %>%
  group_by(Feature, Mod_Type) %>%
  get_summary_stats(DV, type = "mean_sd")
```



```{r}
# Examine RM ANOVA for within and between subject factors including ORDER
res.aov.order3 <- anova_test(
  data = df3, dv = DV, wid = Random_IDs,
  within = c(Sonata_Section, Feature, Mod_Type), between=c(Expertise_Group, Sonata_Order)
  )
get_anova_table(res.aov.order)
```

```{r}

#--------------------------------------------------------------------------------------

# DV2: Ease of Change RM ANOVA

df4 <- readfile <- read.csv("C:/Users/sarah/Documents/Mozart Survey/Data and analysis/Real/df_DV2_NoOut_June20.csv")

View(df4)

str(df4)
```



```{r}

df4 %>%
  group_by(Feature) %>%
  get_summary_stats(DV2, type = "mean_sd")

```


```{r}

bxp2 <- ggboxplot(
  df4, x = "Sonata_Section", y = "DV2",
  color = "Feature", palette = "jco",
  facet.by = "Expertise_Group", short.panel.labs = FALSE
  )
print(bxp2)
```

```{r}

df4 %>%
  group_by(Sonata_Section, Feature, Expertise_Group) %>%
  identify_outliers(DV2)
  
df4 %>%
  group_by(Sonata_Section, Feature) %>%
  shapiro_test(DV2)
  
ggqqplot(df4, "DV2", ggtheme = theme_bw()) +
  facet_grid(Sonata_Section ~ Feature , labeller = "label_both")

df4 %>%
  group_by(Sonata_Section, Feature) %>%
  levene_test(DV2 ~ Expertise_Group)
```

```{r}
# Compute RM ANOVA for within and between subjects factors on DV2

res.aov.bet4 <- anova_test(
  data = df4, dv = DV2, wid = Random_IDs,
  within = c(Sonata_Section, Feature), between=Expertise_Group
  )
get_anova_table(res.aov.bet4, correction="GG")
res.aov.bet4$'Sphericity Corrections'
```


```{r}

# Examine Main Effects for DV2

#Expertise

aov(DV2 ~ Expertise_Group, data = df4) %>% tukey_hsd()

df4 %>% t_test(DV2 ~ Expertise_Group, p.adjust.method = "bonferroni")

df4 %>%
  tukey_hsd(DV2 ~ Expertise_Group, conf.level = 0.95)

df4 %>%
  group_by(Expertise_Group) %>%
  get_summary_stats(DV2, type = "mean_sd")

```
```{r}
#Feature main effect

df4 %>% t_test(DV2 ~ Feature, p.adjust.method = "bonferroni")

df4 %>%
  tukey_hsd(DV2 ~ Feature, conf.level = 0.95)

df4 %>%
  group_by(Feature) %>%
  get_summary_stats(DV2, type = "mean_sd")
```



```{r}
# Sonata Order

res.aov.bet.ord <- anova_test(
  data = df3, dv = DV, wid = Random_IDs,
  within = c(Sonata_Section, Feature, Mod_Type), between=c(Sonata_Order)
  )
get_anova_table(res.aov.bet.ord, correction="GG")
res.aov.bet.ord$`Sphericity Corrections`

```

```

```{r}
res.aov.bet.fam <- anova_test(
  data = df3, dv = DV, wid = Random_IDs,
  within = c(Sonata_Section, Feature, Mod_Type), between=c(Excerpt_Familiarity)
  )
get_anova_table(res.aov.bet.fam, correction="GG")
res.aov.bet.fam$`Sphericity Corrections`
```

